#  curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
version: '2.2'

services:
  uci-messaging-server:
    image: ${UCI_MESSAGING_SERVER:-uci-messaging-server:latest}
    expose:
      - 8080
    environment:
      - TZ=Asia/Shanghai
      - GORM_MASTER_DSN=postgresql://uci:uci123@postgres:5432/uci?sslmode=disable&TimeZone=Asia/Shanghai
      - HTTP_PORT=8080
      - RABBIT_ADDR_URL=amqp://guest:guest@localhost
      - ENABLE_TRACING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - postgres
      - redis
      - rabbitmq
#  uci-dispatch-server:
#    image: ${UCI_DISPATCH_SERVER:-uci-dispatch-server:latest}
#    expose:
#      - 8080
#    environment:
#      - TZ=Asia/Shanghai
#      - GORM_MASTER_DSN=postgresql://uci:uci123@postgres:5432/uci?sslmode=disable&TimeZone=Asia/Shanghai
#      - HTTP_PORT=8080
#      - RABBIT_ADDR_URL=amqp://guest:guest@localhost
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq
volumes:
  redis-data: {}
  pg-data: {}


#failed to initialize database, got error failed to connect to `host=/tmp user=uci database=uci`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)