version: '2.2'

services:
  redis:
#    https://hub.docker.com/_/redis
    image: redis:5.0.14
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.9
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - ./infra/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
#      - ./infra/rabbitmq/auth.conf:/etc/rabbitmq/conf.d/auth.conf
  nginx:
    image: nginx:1.21.6
    expose:
      - "80"
    ports:
      - "80:80"
  uci-messaging-server:
    image: ${UCI_MESSAGING_SERVER:-uci-messaging-server:latest}
    expose:
      - "8080"
    ports:
      - "8080:8080"
volumes:
  redis-data: {}