#  curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
version: '2.2'

services:
  uci-messaging-server:
    image: ${UCI_MESSAGING_SERVER:-uci-messaging-server:latest}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
volumes:
  redis-data: {}
  pg-data: {}