#  curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
version: '2.2'

services:
  uci-messaging-server:
    image: ${UCI_MESSAGING_SERVER:-uci-messaging-server:latest}
    expose:
      - 8080
    environment:
      - TZ=Asia/Shanghai
      - GORM_MASTER_DSN="host=postgres user=uci password=uci123 dbname=uci port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      - HTTP_PORT=8080
volumes:
  redis-data: {}
  pg-data: {}