#  curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#这个版本也是 Ok 的v2:21:0

version: '2.2'

services:
#  uci-messaging-server:
#    image: ${UCI_MESSAGING_SERVER:-uci-messaging-server:latest}
#    expose:
#      - 8080
#    environment:
#      - TZ=Asia/Shanghai
#      - GORM_MASTER_DSN=root:uci123@tcp(mysql:3306)/uci?charset=utf8mb4&parseTime=True&loc=Local
#      - HTTP_PORT=8080
#      - RABBIT_ADDR_URL=amqp://guest:guest@rabbitmq
#    depends_on:
#      - mysql
#      - redis
#      - rabbitmq
#  uci-dispatch-server:
#    image: ${UCI_DISPATCH_SERVER:-uci-dispatch-server:latest}
#    expose:
#      - 8080
#    environment:
#      - TZ=Asia/Shanghai
#      - GORM_MASTER_DSN=postgresql://uci:uci123@postgres:5432/uci?sslmode=disable&TimeZone=Asia/Shanghai
#      - HTTP_PORT=8080
#      - RABBIT_ADDR_URL=amqp://guest:guest@localhost
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq

  uci-master:
    image: ${UCI_MASTER_IMAGE:-uci-master:latest}
    expose:
      - 8080
    environment:
      - TZ=Asia/Shanghai
      - GORM_MASTER_DSN=root:uci123@tcp(mysql:3306)/uci?charset=utf8mb4&parseTime=True&loc=Local
      - HTTP_PORT=8080
      - RABBIT_ADDR_URL=amqp://guest:guest@rabbitmq
      - REDIS_DSN=redis:6379
    depends_on:
      - mysql
      - redis
      - rabbitmq

#failed to initialize database, got error failed to connect to `host=/tmp user=uci database=uci`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)